### ISSUE TITLE
Rewrite bank account using OTP

### ISSUE THREAD

**Issue by pdincau** [joebew42/twitch#2]
It would be great to see you rewrite the bank account using OTP. What do you think? In this way you could explore OTP, different behaviours and supervision tree

**Comment by 0xNaN** [comment]
I thought the same thing however doing a refactoring: implementing all the messages logic and then refactoring it to a Gen* could be a good way to introduce OTP and discuss/learning about interesting topics such as:

 - what is OTP and what benefit it offers
      - structure of an OTP application
      - Gen*
      - supervisor
      - ...
 - how it affects the tests done so far (I'm interested to hear about testing a genserver)

I think you can explore this topics separately....anyway thank you for this work! :muscle:
