### ISSUE TITLE
Create a ExTwitch Library

### ISSUE THREAD

**Issue by joebew42** [joebew42/twitch#35]
# ExTwitch

A client implementation for the new Twitch API

The project [can be found here](https://github.com/joebew42/ex_twitch)

**Comment by jluiiizz** [comment]
I think this idea very nice. It would be fun, innovating and instructive see this kind of development with elixir. I really think that is a very good project.

**Comment by joebew42** [comment]
Thank you for your feedback.

This could be an interesting topic to go with, we could spend a week or two in trying to figure out how to build a client library for the Twitch API. Of course, I think it will be an activity of _learning_ and _exploring_, just because I don't think to have the time to continue to mantain a project like that. Maybe, I could start and then we can look for someone who wants to continue to mantain it. BTW, we will start with this :rocket:

**Comment by joebew42** [comment]
We ended up by creating a working client implementation for the new Twitch API, the project is here: https://github.com/joebew42/ex_twitch

Now we will wait for new contributors!
